using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Arbor.ModelBinding.Generators;

[Generator(LanguageNames.CSharp)]
public class FormBinderIncrementalGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol?> bindableTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: "Arbor.ModelBinding.Core.BindableAttribute",
                predicate: (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax or StructDeclarationSyntax,
                transform: (ctx, _) => ctx.TargetSymbol as INamedTypeSymbol)
            .Where(symbol => symbol is not null);

        context.RegisterSourceOutput(bindableTypes, (spc, symbol) => EmitBinder(spc, symbol!));
    }

    private static void EmitBinder(SourceProductionContext context, INamedTypeSymbol typeSymbol)
    {
        string ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? "Arbor.ModelBinding.Generated"
            : $"{typeSymbol.ContainingNamespace.ToDisplayString()}.Generated";

        string typeName = typeSymbol.Name;
        string binderName = $"FormBinder_{typeName}";
        string fullType = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string fullTypeDisplayName = typeSymbol.ToDisplayString();

        var properties = GetBindableProperties(typeSymbol).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("#nullable enable");
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine($"    internal sealed class {binderName} : Arbor.ModelBinding.Core.IFormBinder<{fullType}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        public Arbor.ModelBinding.Core.FormBindResult<{fullType}> Bind(Arbor.ModelBinding.Core.FormDataReader reader)");
        sb.AppendLine("        {");

        foreach (var prop in properties)
        {
            string name = prop.Name;
            string type = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            bool has{name} = false;");
            sb.AppendLine($"            {type} __{Camel(name)} = default!;");
        }

        sb.AppendLine("            reader.Reset();");
        sb.AppendLine("            while (reader.MoveNext())");
        sb.AppendLine("            {");
        sb.AppendLine("                var key = reader.CurrentKey;");
        sb.AppendLine();

        for (int i = 0; i < properties.Count; i++)
        {
            var prop = properties[i];
            string name = prop.Name;
            string @if = i == 0 ? "if" : "else if";
            sb.AppendLine($"                {@if} (key.Equals(\"{name}\", System.StringComparison.OrdinalIgnoreCase))");
            sb.AppendLine("                {");
            sb.AppendLine(ParseBlock(prop, Camel(name), fullType));
            sb.AppendLine($"                    has{name} = true;");
            sb.AppendLine("                    continue;");
            sb.AppendLine("                }");
        }

        sb.AppendLine("            }");
        sb.AppendLine();

        foreach (var prop in properties)
        {
            if (!IsNullable(prop.Type))
            {
                string name = prop.Name;
                sb.AppendLine($"            if (!has{name})");
                sb.AppendLine("            {");
                sb.AppendLine($"                return Arbor.ModelBinding.Core.FormBindResult<{fullType}>.Failure(new[] {{ new Arbor.ModelBinding.Core.FormBindError(\"{name}\", \"Required field missing\") }});");
                sb.AppendLine("            }");
                sb.AppendLine();
            }
        }

        sb.AppendLine($"            return Arbor.ModelBinding.Core.FormBindResult<{fullType}>.Success(new {fullType}");
        sb.AppendLine("            {");
        for (int i = 0; i < properties.Count; i++)
        {
            string comma = i == 0 ? "" : ",";
            string name = properties[i].Name;
            sb.AppendLine($"                {comma}{name} = __{Camel(name)}");
        }
        sb.AppendLine("            });");
        sb.AppendLine("        }");
        foreach (var prop in properties)
        {
            if (prop.Type.ToDisplayString() is "bool" or "System.Boolean")
            {
                sb.AppendLine(EmitTryParseBoolHelper(Camel(prop.Name)));
            }
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{binderName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string ParseBlock(IPropertySymbol prop, string variable, string fullType)
    {
        string sv = $"reader.CurrentValue.ToString()";
        string type = prop.Type.ToDisplayString();

        return type switch
        {
            "int" or "System.Int32" =>
                $"                    if (!int.TryParse({sv}, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out __{variable}))\n" +
                $"                        return Arbor.ModelBinding.Core.FormBindResult<{fullType}>.Failure(new[] {{ new Arbor.ModelBinding.Core.FormBindError(key, \"Could not parse Int32\") }});\n",

            "string" or "System.String" =>
                $"                    __{variable} = {sv} ?? string.Empty;\n",

            "bool" or "System.Boolean" =>
                $"                    if (!TryParseBool_{variable}({sv}, out __{variable}))\n" +
                $"                        return Arbor.ModelBinding.Core.FormBindResult<{fullType}>.Failure(new[] {{ new Arbor.ModelBinding.Core.FormBindError(key, \"Could not parse Boolean\") }});\n",

            _ => $"                    __{variable} = {sv}; // fallback for {type}\n"
        };
    }

    private static string EmitTryParseBoolHelper(string variable)
    {
        return $@"
        private static bool TryParseBool_{variable}(string? raw, out bool value)
        {{
            value = false;
            if (string.IsNullOrEmpty(raw)) {{ value = false; return true; }}
            if (string.Equals(raw, ""true"", System.StringComparison.OrdinalIgnoreCase) ||
                string.Equals(raw, ""1"", System.StringComparison.OrdinalIgnoreCase) ||
                string.Equals(raw, ""on"", System.StringComparison.OrdinalIgnoreCase) ||
                string.Equals(raw, ""yes"", System.StringComparison.OrdinalIgnoreCase))
            {{ value = true; return true; }}
            if (string.Equals(raw, ""false"", System.StringComparison.OrdinalIgnoreCase) ||
                string.Equals(raw, ""0"", System.StringComparison.OrdinalIgnoreCase) ||
                string.Equals(raw, ""off"", System.StringComparison.OrdinalIgnoreCase) ||
                string.Equals(raw, ""no"", System.StringComparison.OrdinalIgnoreCase))
            {{ value = false; return true; }}
            return false;
        }}
";
    }

    private static IEnumerable<IPropertySymbol> GetBindableProperties(INamedTypeSymbol typeSymbol) =>
        typeSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic && p.SetMethod is not null);

    private static string Camel(string name) => char.ToLowerInvariant(name[0]) + name.Substring(1);

    private static bool IsNullable(ITypeSymbol type) =>
        type.NullableAnnotation == NullableAnnotation.Annotated
        || (type is INamedTypeSymbol nts && nts.IsGenericType && nts.Name == "Nullable");
}
